#!/bin/ruby

# script to disassemble a short patch of code
# beginning at a specified address
# we give the address as an offset in hex into the rom.

if ARGV.size < 1
    puts "Insert coin"
    exit
end

#off = 0xe0
off = ARGV[0].hex

elf = "bootsym.elf"
dis = "xtensa-lx106-elf-objdump -mxtensa -d #{elf} -z "

base = 0x40000000

count = 128
ss = "%08x" % (base + off)
es = "%08x" % (base + off + count)

range = "--start-address=0x#{ss} --stop-address=0x#{es}"

cmd = dis + range
#puts cmd
system cmd

# THE END
